# Site settings
# in the templates available like {{ site.myvariable }}.
title: This is Adam and Amanda's personal place.
email: adamchendd@gmail.com
brand: Adam -- Amanda
headline: Past, Now and Future
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://adamchendd.github.io" # the base hostname & protocol for your site
copyright: 2017 Adam&Amanda. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: adamchendd@gmail.com
phone: +86-186-8200-3502

# Tracking
googleAnalitycsID: UA-83933844-1

